
controls:

  - name: "Physical Address"
    has_labels: false
    has_control: true
    items:
      - control:
          position: [0, 0]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 5

  - name: "Addresses Same"
    has_labels: false
    has_control: true
    items:
      - control:
          position: [1, 0]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 5

  - name: "Postal Address"
    has_labels: false
    has_control: true
    items:
      - control:
          position: [2, 0]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 5
  - name: "InfoBar"
    has_labels: false
    has_control: true
    items:
      - control:
          position: [3, 0]
          span: [2, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"] #, "wxRESERVE_SPACE_EVEN_IF_HIDDEN"]
          borderWidth: 5
