controls:

  - name: "Existing Addresses"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [1, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 6
      - control:
          position: [1, 1]
          span: [1, 4]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Address Line 1"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [3, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 6
      - control:
          position: [3, 1]
          span: [1, 4]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Address Line 2"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [4, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 6
      - control:
          position: [4, 1]
          span: [1, 4]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "City"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [5, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 6
      - control:
          position: [5, 1]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "State or Provence"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [5, 2]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 6
      - control:
          position: [5, 3]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Postal Code"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [6, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 6
      - control:
          position: [6, 1]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Country"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [6, 2]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [6, 3]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3
