breaks:
  - after: ["Address Selector", "Physical Address", "Postal Address"]

controls:
  - name: "Address Selector"
    has_labels: false
    has_control: true
    items:
      - control:
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]

  - name: "Physical Address"
    has_labels: false
    has_control: true
    items:
      - control:
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]

  - name: "Postal Address"
    has_labels: false
    has_control: true
    items:
      - control:
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]

  - name: "InfoBar"
    has_labels: false
    has_control: true
    items:
      - control:
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"] #, "wxRESERVE_SPACE_EVEN_IF_HIDDEN"]
