controls:

  - name: "Filename"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [0, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxRIGHT", "wxTOP", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [0, 1]
          span: [1, 9]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxLEFT", "wxTOP", "wxGROW"]
          borderWidth: 5

  - name: "Select"
    has_labels: false
    has_control: true
    has_gap: false
    items:
      - control:
          position: [0, 10]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxLEFT", "wxTOP"]
          borderWidth: 5

  - name: "InfoBar"
    has_labels: false
    has_control: true
    has_gap: false
    items:
      - control:
          position: [1, 0]
          span: [2, 10]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxLEFT", "wxTOP", "wxGROW"]
          borderWidth: 5
