breaks:
  - after: ["Name Details", "Datafile"]

controls:

  - name: "Name Details"
    has_labels: false
    has_control: true
    items:
      - control:
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]

  - name: "Datafile"
    has_labels: false
    has_control: true
    items:
      - control:
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]

  - name: "InfoBar"
    has_labels: false
    has_control: true
    items:
      - control:
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
