controls:

  - name: "Title"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [1, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxRIGHT", "wxTOP", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [1, 1]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxLEFT", "wxTOP", "wxGROW"]
          borderWidth: 3

  - name: "Given Name"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [2, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxRIGHT", "wxTOP", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [2, 1]
          span: [1, 4]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxLEFT", "wxTOP", "wxGROW"]
          borderWidth: 3

  - name: "Family Name"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [3, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxRIGHT", "wxTOP", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [3, 1]
          span: [1, 4]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxLEFT", "wxTOP", "wxGROW"]
          borderWidth: 3

  - name: "Family name comes first"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [4, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxRIGHT", "wxTOP", "wxALIGN_RIGHT"]
            borderWidth: 3
          - which: "LIX::Second"
            position: [5, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxRIGHT", "wxTOP", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [4, 1]
          span: [2, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxLEFT", "wxTOP"]
          borderWidth: 3

  - name: "Mobile Phone"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [7, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxRIGHT", "wxTOP", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [7, 1]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxLEFT", "wxTOP", "wxGROW"]
          borderWidth: 3

  - name: "Landline"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [8, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxRIGHT", "wxTOP", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [8, 1]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxLEFT", "wxTOP", "wxGROW"]
          borderWidth: 3

  - name: "Date of Birth"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [7, 2]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxRIGHT", "wxTOP", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [7, 3]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxLEFT", "wxTOP", "wxGROW"]
          borderWidth: 3

  - name: "Fax Line"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [7, 2]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxRIGHT", "wxTOP", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [7, 3]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxLEFT", "wxTOP", "wxGROW"]
          borderWidth: 3

  - name: "Email Address"
    has_labels: true
    has_control: true
    has_gap: false
    items:
      - labels:
          - which: "LIX::Main"
            position: [8, 2]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxRIGHT", "wxTOP", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [8, 3]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxLEFT", "wxTOP", "wxGROW"]
          borderWidth: 3

  - name: "InfoBar"
    has_labels: false
    has_control: true
    has_gap: false
    items:
      - control:
          position: [9, 0]
          span: [2, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxLEFT", "wxTOP", "wxGROW"]
          borderWidth: 3
