breaks:
  - after: [ "Family Name", "Type", "[Family Name First]" ]

controls:
  - name: "Given Name"
    has_labels: true
    has_control: true
    items:
      - labels:
          flags: [ "wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT" ]
      - control:
          flags: [ "wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW" ]

  - name: "Family Name"
    has_labels: true
    has_control: true
    items:
      - labels:
          flags: [ "wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT" ]
      - control:
          flags: [ "wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW" ]

  - name: "Title"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            flags: [ "wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT" ]
      - control:
          flags: [ "wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW" ]

  - name: "Type"
    has_labels: true
    has_control: true
    items:
      - labels:
          flags: [ "StdLabelFlags", "wxRESERVE_SPACE_EVEN_IF_HIDDEN"]
      - control:
          flags: [ "StdControlFlags", "wxRESERVE_SPACE_EVEN_IF_HIDDEN"]

  - name: "Family Name First"
    has_labels: true
    has_control: true
    items:
      - control:
          flags: [ "wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT" ]
      - labels:
          - which: "LIX:Main"
            flags: [ "LeftAlignedLabelFlags" ]
          - which: "LIX:Second"
            span: [ 1, 2 ]
            flags: [ "StdLabelFlags", "wxGROW" ]
