controls:

  - name: "Title"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [1, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [1, 1]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Date of Birth"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [1, 2]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [1, 3]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Given Name"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [2, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [2, 1]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Family Name"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [2, 2]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [2, 3]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Want Popup Alerts"
    has_labels: true
    has_control: true
    items:
      - control:
          position: [4, 0]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALIGN_RIGHT"]
          borderWidth: 3
      - labels:
          - which: "LIX::Main"
            position: [4, 1]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL"]
            borderWidth: 3

  - name: "Have PBS Concession"
    has_labels: true
    has_control: true
    items:
      - control:
          position: [4, 2]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALIGN_RIGHT"]
          borderWidth: 3
      - labels:
          - which: "LIX::Main"
            position: [4, 3]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL"]
            borderWidth: 3

  - name: "Want SMS Alerts"
    has_labels: true
    has_control: true
    items:
      - control:
          position: [5, 0]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALIGN_RIGHT"]
          borderWidth: 3
      - labels:
          - which: "LIX::Main"
            position: [5, 1]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL"]
            borderWidth: 3

  - name: "GP"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [5, 2]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [5, 3]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Want Email Alerts"
    has_labels: true
    has_control: true
    items:
      - control:
          position: [6, 0]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALIGN_RIGHT"]
          borderWidth: 3
      - labels:
          - which: "LIX::Main"
            position: [6, 1]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL"]
            borderWidth: 3

  - name: "Pharmacist"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [6, 2]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [6, 3]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Mobile Phone"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [8, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [8, 1]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Landline"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [8, 2]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [8, 3]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Fax Line"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [9, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [9, 1]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Email Address"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [9, 2]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [9, 3]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "InfoBar"
    has_labels: false
    has_control: true
    items:
      - control:
          position: [10, 0]
          span: [2, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3
