controls:

  - name: "Given Name"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [1, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [1, 1]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Family Name"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [1, 2]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [1, 3]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Title"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [2, 0]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [2, 1]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Date of Birth"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [2, 2]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [2, 3]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3

  - name: "Type"
    has_labels: true
    has_control: true
    items:
      - labels:
          - which: "LIX::Main"
            position: [2, 2]
            span: [1, 1]
            flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxALIGN_RIGHT"]
            borderWidth: 3
      - control:
          position: [2, 3]
          span: [1, 1]
          flags: ["wxALIGN_CENTRE_VERTICAL", "wxALL", "wxGROW"]
          borderWidth: 3
